# CTR Prediction

	https://www.kaggle.com/c/avazu-ctr-prediction/data

## File descriptions
**train** - Training set. 10 days of click-through data, ordered chronologically. Non-clicks and clicks are subsampled according to different strategies. 

	https://www.kaggle.com/c/avazu-ctr-prediction/download/train.gz

**test** - Test set. 1 day of ads to for testing your model predictions. 

	https://www.kaggle.com/c/avazu-ctr-prediction/download/test.gz

**sampleSubmission.csv** - Sample submission file in the correct format, corresponds to the All-0.5 Benchmark. 

	https://www.kaggle.com/c/avazu-ctr-prediction/download/sampleSubmission.gz

## Data fields
id: ad identifier
click: 0/1 for non-click/click
hour: format is YYMMDDHH, so 14091123 means 23:00 on Sept. 11, 2014 UTC.

C1 -- anonymized categorical variable, banner_pos, site_id, site_domain, site_category, app_id, app_domain, app_category, device_id, device_ip, device_model, device_type, device_conn_type, C14-C21 -- anonymized categorical variables

# 数据分析与处理

## 1 下采样（对大型数据）

## 2 导入数据

In [2]:
import pandas as pd


# Initial setup
train_filename = "train_small.csv"
test_filename = "test.csv"
submission_filename = "submit.csv"

training_set = pd.read_csv(train_filename)

**数据监测**

In [3]:
training_set.head(10)

id  click      hour    C1  banner_pos   site_id site_domain  \
0  1.000009e+18      0  14102100  1005           0  1fbe01fe    f3845767   
1  1.000017e+19      0  14102100  1005           0  1fbe01fe    f3845767   
2  1.000037e+19      0  14102100  1005           0  1fbe01fe    f3845767   
3  1.000064e+19      0  14102100  1005           0  1fbe01fe    f3845767   
4  1.000068e+19      0  14102100  1005           1  fe8cc448    9166c161   
5  1.000072e+19      0  14102100  1005           0  d6137915    bb1ef334   
6  1.000072e+19      0  14102100  1005           0  8fda644b    25d4cfcd   
7  1.000092e+19      0  14102100  1005           1  e151e245    7e091613   
8  1.000095e+19      1  14102100  1005           0  1fbe01fe    f3845767   
9  1.000126e+19      0  14102100  1002           0  84c7ba46    c4e18dd6   

  site_category    app_id app_domain  ... device_type device_conn_type    C14  \
0      28905ebd  ecad2386   7801e8d9  ...           1                2  15706   
1      28905ebd  ecad2386   7801e8d9  ...           1                0  15704   
2      28905ebd  ecad2386   7801e8d9  ...           1                0  15704   
3      28905ebd  ecad2386   7801e8d9  ...           1                0  15706   
4      0569f928  ecad2386   7801e8d9  ...           1                0  18993   
5      f028772b  ecad2386   7801e8d9  ...           1                0  16920   
6      f028772b  ecad2386   7801e8d9  ...           1                0  20362   
7      f028772b  ecad2386   7801e8d9  ...           1                0  20632   
8      28905ebd  ecad2386   7801e8d9  ...           1                2  15707   
9      50e219e0  ecad2386   7801e8d9  ...           0                0  21689   

   C15  C16   C17  C18  C19     C20  C21  
0  320   50  1722    0   35      -1   79  
1  320   50  1722    0   35  100084   79  
2  320   50  1722    0   35  100084   79  
3  320   50  1722    0   35  100084   79  
4  320   50  2161    0   35      -1  157  
5  320   50  1899    0  431  100077  117  
6  320   50  2333    0   39      -1  157  
7  320   50  2374    3   39      -1   23  
8  320   50  1722    0   35      -1   79  
9  320   50  2496    3  167  100191   23  

[10 rows x 24 columns]

In [4]:
training_set.describe()

id         click        hour            C1    banner_pos  \
count  9.999900e+04  99999.000000     99999.0  99999.000000  99999.000000   
mean   9.500834e+18      0.174902  14102100.0   1005.034440      0.198302   
std    5.669435e+18      0.379885         0.0      1.088705      0.402641   
min    3.237563e+13      0.000000  14102100.0   1001.000000      0.000000   
25%    4.183306e+18      0.000000  14102100.0   1005.000000      0.000000   
50%    1.074496e+19      0.000000  14102100.0   1005.000000      0.000000   
75%    1.457544e+19      0.000000  14102100.0   1005.000000      0.000000   
max    1.844670e+19      1.000000  14102100.0   1010.000000      5.000000   

        device_type  device_conn_type           C14           C15  \
count  99999.000000      99999.000000  99999.000000  99999.000000   
mean       1.055741          0.199272  17682.106071    318.333943   
std        0.583986          0.635271   3237.726956     11.931998   
min        0.000000          0.000000    375.000000    120.000000   
25%        1.000000          0.000000  15704.000000    320.000000   
50%        1.000000          0.000000  17654.000000    320.000000   
75%        1.000000          0.000000  20362.000000    320.000000   
max        5.000000          5.000000  21705.000000    728.000000   

                C16           C17           C18           C19            C20  \
count  99999.000000  99999.000000  99999.000000  99999.000000   99999.000000   
mean      56.818988   1964.029090      0.789328    131.735447   37874.606366   
std       36.924283    394.961129      1.223747    244.077816   48546.369299   
min       20.000000    112.000000      0.000000     33.000000      -1.000000   
25%       50.000000   1722.000000      0.000000     35.000000      -1.000000   
50%       50.000000   1993.000000      0.000000     35.000000      -1.000000   
75%       50.000000   2306.000000      2.000000     39.000000  100083.000000   
max      480.000000   2497.000000      3.000000   1835.000000  100248.000000   

                C21  
count  99999.000000  
mean      88.555386  
std       45.482979  
min       13.000000  
25%       61.000000  
50%       79.000000  
75%      156.000000  
max      157.000000

## 数据预处理

In [5]:
data_train = pd.read_csv('train_small.csv',header=0)

In [6]:
data_train.head()

id  click      hour    C1  banner_pos   site_id site_domain  \
0  1.000009e+18      0  14102100  1005           0  1fbe01fe    f3845767   
1  1.000017e+19      0  14102100  1005           0  1fbe01fe    f3845767   
2  1.000037e+19      0  14102100  1005           0  1fbe01fe    f3845767   
3  1.000064e+19      0  14102100  1005           0  1fbe01fe    f3845767   
4  1.000068e+19      0  14102100  1005           1  fe8cc448    9166c161   

  site_category    app_id app_domain  ... device_type device_conn_type    C14  \
0      28905ebd  ecad2386   7801e8d9  ...           1                2  15706   
1      28905ebd  ecad2386   7801e8d9  ...           1                0  15704   
2      28905ebd  ecad2386   7801e8d9  ...           1                0  15704   
3      28905ebd  ecad2386   7801e8d9  ...           1                0  15706   
4      0569f928  ecad2386   7801e8d9  ...           1                0  18993   

   C15  C16   C17  C18  C19     C20  C21  
0  320   50  1722    0   35      -1   79  
1  320   50  1722    0   35  100084   79  
2  320   50  1722    0   35  100084   79  
3  320   50  1722    0   35  100084   79  
4  320   50  2161    0   35      -1  157  

[5 rows x 24 columns]

**去除掉train数据集中的类别数据，保留数值型数据**

In [7]:
data_train = data_train.drop(['site_id', 'app_id', 'device_id', 'device_ip', 'site_domain',
                  'site_category', 'app_domain', 'app_category', 'device_model'], axis=1)

In [8]:
data_train.head()

id  click      hour    C1  banner_pos  device_type  \
0  1.000009e+18      0  14102100  1005           0            1   
1  1.000017e+19      0  14102100  1005           0            1   
2  1.000037e+19      0  14102100  1005           0            1   
3  1.000064e+19      0  14102100  1005           0            1   
4  1.000068e+19      0  14102100  1005           1            1   

   device_conn_type    C14  C15  C16   C17  C18  C19     C20  C21  
0                 2  15706  320   50  1722    0   35      -1   79  
1                 0  15704  320   50  1722    0   35  100084   79  
2                 0  15704  320   50  1722    0   35  100084   79  
3                 0  15706  320   50  1722    0   35  100084   79  
4                 0  18993  320   50  2161    0   35      -1  157

In [9]:
data_train = data_train.drop(['id'], axis=1)

In [10]:
data_train.head()

click      hour    C1  banner_pos  device_type  device_conn_type    C14  \
0      0  14102100  1005           0            1                 2  15706   
1      0  14102100  1005           0            1                 0  15704   
2      0  14102100  1005           0            1                 0  15704   
3      0  14102100  1005           0            1                 0  15706   
4      0  14102100  1005           1            1                 0  18993   

   C15  C16   C17  C18  C19     C20  C21  
0  320   50  1722    0   35      -1   79  
1  320   50  1722    0   35  100084   79  
2  320   50  1722    0   35  100084   79  
3  320   50  1722    0   35  100084   79  
4  320   50  2161    0   35      -1  157

In [11]:
data_train = data_train.values

In [12]:
data_train

array([[       0, 14102100,     1005, ...,       35,       -1,       79],
       [       0, 14102100,     1005, ...,       35,   100084,       79],
       [       0, 14102100,     1005, ...,       35,   100084,       79],
       ...,
       [       0, 14102100,     1005, ...,       35,       -1,       79],
       [       1, 14102100,     1005, ...,       35,       -1,       79],
       [       0, 14102100,     1005, ...,       35,       -1,       79]],
      dtype=int64)

In [13]:
data_train[:,:]

array([[       0, 14102100,     1005, ...,       35,       -1,       79],
       [       0, 14102100,     1005, ...,       35,   100084,       79],
       [       0, 14102100,     1005, ...,       35,   100084,       79],
       ...,
       [       0, 14102100,     1005, ...,       35,       -1,       79],
       [       1, 14102100,     1005, ...,       35,       -1,       79],
       [       0, 14102100,     1005, ...,       35,       -1,       79]],
      dtype=int64)

In [14]:
data_train.shape

(99999, 14)

In [16]:
data_train[0::,0]

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [17]:
data_train[0::,1::]

array([[14102100,     1005,        0, ...,       35,       -1,       79],
       [14102100,     1005,        0, ...,       35,   100084,       79],
       [14102100,     1005,        0, ...,       35,   100084,       79],
       ...,
       [14102100,     1005,        0, ...,       35,       -1,       79],
       [14102100,     1005,        0, ...,       35,       -1,       79],
       [14102100,     1005,        0, ...,       35,       -1,       79]],
      dtype=int64)

**模型选择，交叉验证**

In [19]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

# 性能度量
from sklearn import metrics

In [32]:
X_train,X_test,y_train,y_test = train_test_split(data_train[0::,1::],data_train[0::,0],test_size=0.3,random_state=0) 

model = LogisticRegression(solver='lbfgs')
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [33]:
prediction = model.predict(X_test)

**性能度量**

In [38]:
def print_metrics(true_values,predicted_values):
    accuracy = metrics.accuracy_score(true_values,predicted_values)
    auc = metrics.roc_auc_score(true_values,predicted_values)
    Confiusize_matrix = metrics.confusion_matrix(true_values,predicted_values)
    class_report = metrics.classification_report(true_values,predicted_values,labels=np.unique(predicted_values))
    print("Accuracy = ",accuracy)
    print("AUC = ",auc)
    print("Confusion Matrix = ",Confiusize_matrix)
    print(class_report)

In [39]:
print_metrics(y_test,prediction)

Accuracy =  0.8233
AUC =  0.5
Confusion Matrix =  [[24699     0]
 [ 5301     0]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90     24699

   micro avg       0.82      1.00      0.90     24699
   macro avg       0.82      1.00      0.90     24699
weighted avg       0.82      1.00      0.90     24699



**保存模型**

In [41]:
from sklearn.externals import joblib

In [43]:
joblib.dump(model,'classifier.pkl')

['classifier.pkl']

**<font size=4 color=red>上述操作生成了最基本、最原始的baseline for classification LR model</font>**

**按照指定的格式生成结果**

In [44]:
import numpy as np
from pandas import DataFrame

In [45]:
def create_submission(ids,prediction,filename='submission.csv'):
    submission = np.concatenate((ids.reshape(len(ids),1),prediction.reshape(len(prediction),1)),axis=1)
    data = DataFrame(submission)
    data.to_csv(filename,header=['id','click'],index=False)

In [47]:
classifer_LR = joblib.load('classifier.pkl')
data_test = pd.read_csv('test.csv')
data_test = data_test.drop(['site_id', 'app_id', 'device_id', 'device_ip', 'site_domain',
                  'site_category', 'app_domain', 'app_category', 'device_model'], axis=1)

In [49]:
ids = data_test.values[0:,0]
prediction = classifer_LR.predict(data_test.values[0:,1:])


**生成结果**

In [50]:
create_submission(ids,prediction)

In [ ]:
# id: ad identifier
# click: 0/1 for non-click/click
# hour: format is YYMMDDHH, so 14091123 means 23:00 on Sept. 11, 2014 UTC.
# C1 -- anonymized categorical variable
# banner_pos
# site_id
# site_domain
# site_category
# app_id
# app_domain
# app_category
# device_id
# device_ip
# device_model
# device_type
# device_conn_type
# C14-C21 -- anonymized categorical variables
from sklearn.externals import joblib   # 保存模型
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

from utils import load_df

In [ ]:
# 结果衡量
def print_metrics(true_values, predicted_values):
    print("Accuracy: ", metrics.accuracy_score(true_values, predicted_values))
    print("AUC: ", metrics.roc_auc_score(true_values, predicted_values)) "AUC: ", metrics.roc_auc_score(true_values, predicted_values)
    print("Confusion Matrix: ", + metrics.confusion_matrix(true_values, predicted_values)) "Confusion Matrix: ", + metrics.confusion_matrix(true_values, predicted_values)
    print(metrics.classification_report(true_values, predicted_values)) metrics.classification_report(true_values, predicted_values)

# 拟合分类器
def classify(classifier_class, train_input, train_targets):
    classifier_object = classifier_class()
    classifier_object.fit(train_input, train_targets)
    return classifier_object

# 模型存储
def save_model(clf):
    joblib.dump(clf, 'classifier.pkl')